# Generated by Django 4.2 on 2023-08-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentance', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=150)),
                ('sentance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150)),
                ('sentance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.quizquestion')),
            ],
        ),
    ]
