# Generated by Django 4.2 on 2023-08-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_quizquestion_quizchoice_quizans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='word',
            field=models.CharField(default='Error', max_length=120),
        ),
    ]
